export class TournamentError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'TournamentError';
    this.code = code;
    Object.assign(this, details);
  }
}

export const ErrorCodes = {
  NO_FORMAT: 'NO_FORMAT',
  NO_PLAYERS: 'NO_PLAYERS',
  TOO_FEW_PLAYERS: 'TOO_FEW_PLAYERS',
  INCOMPLETE_ROUND: 'INCOMPLETE_ROUND',
  TOURNAMENT_COMPLETED: 'TOURNAMENT_COMPLETED',
  INVALID_ROUND: 'INVALID_ROUND',
  INVALID_TABLE: 'INVALID_TABLE',
  INVALID_RESULT: 'INVALID_RESULT',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  DUPLICATE_PLAYER: 'DUPLICATE_PLAYER',
  TOURNAMENT_STARTED: 'TOURNAMENT_STARTED',
  PLAYER_ALREADY_WITHDRAWN: 'PLAYER_ALREADY_WITHDRAWN',
  PLAYER_NOT_WITHDRAWN: 'PLAYER_NOT_WITHDRAWN',
  FORMAT_LOCKED: 'FORMAT_LOCKED',
  PAIRING_FAILED: 'PAIRING_FAILED',
};
